package vista;

import controlador.ControladorNuevoDetalle;
import javax.swing.event.TableModelEvent; //
import javax.swing.event.TableModelListener; //
import javax.swing.table.DefaultTableModel;

public class VistaNuevoDetalle extends javax.swing.JFrame {

    /**
     * Creates new form VistaNuevoDetalle
     */
    public VistaNuevoDetalle() {
        initComponents();
        ControladorNuevoDetalle.ActualizarTablaProductos(tablaProductos);
        ControladorNuevoDetalle.IniciarTablaDetalles(tablaDetalles);
        ControladorNuevoDetalle.ActualizarTablaClientes(tablaClientes);
        ControladorNuevoDetalle.AjustarTabla(tablaProductos);
        ControladorNuevoDetalle.AjustarTabla(tablaDetalles);
        ControladorNuevoDetalle.AjustarTabla(tablaClientes);
        ControladorNuevoDetalle.ValidarCantidad(txtCantidad);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        btnCancelarCompra = new javax.swing.JButton();
        btnAñadir = new javax.swing.JButton();
        btnQuitar = new javax.swing.JButton();
        btnFacturar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txtCodigo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        txtIdCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtNombreCliente = new javax.swing.JTextField();
        txtPreciou = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaDetalles = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        lblTotalAPagar = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tablaClientes = new javax.swing.JTable();
        txtBuscarProducto = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblLimpiarBusquedaProducto = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBuscarCliente = new javax.swing.JTextField();
        lblLimpiarBusquedaCliente = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuProductos = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenuItem();
        menuMaestroDetalle = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(41, 41, 41));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Detalle Venta", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));

        jPanel2.setBackground(new java.awt.Color(84, 84, 84));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Realizar Venta");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 258, -1));

        jLabel3.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nombre Cliente");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 130, -1));

        txtDescripcion.setEditable(false);
        txtDescripcion.setBackground(new java.awt.Color(84, 84, 84));
        txtDescripcion.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(153, 153, 153));
        txtDescripcion.setBorder(null);
        jPanel2.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 220, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 220, 10));

        txtCantidad.setBackground(new java.awt.Color(84, 84, 84));
        txtCantidad.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(153, 153, 153));
        txtCantidad.setBorder(null);
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 220, 60, 30));

        jLabel4.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 70, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 220, 10));

        jLabel8.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Precio Unitario");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 100, -1));

        btnCancelarCompra.setText("Cancelar Compra");
        btnCancelarCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCompraActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelarCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 460, 140, -1));

        btnAñadir.setText("Añadir Articulo");
        btnAñadir.setEnabled(false);
        btnAñadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAñadirActionPerformed(evt);
            }
        });
        jPanel2.add(btnAñadir, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 140, -1));

        btnQuitar.setText("Quitar Articulo");
        btnQuitar.setEnabled(false);
        btnQuitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitarActionPerformed(evt);
            }
        });
        jPanel2.add(btnQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 140, -1));

        btnFacturar.setText("Facturar");
        btnFacturar.setEnabled(false);
        btnFacturar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturarActionPerformed(evt);
            }
        });
        jPanel2.add(btnFacturar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 140, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 140, -1));

        jLabel14.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Codigo Articulo");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, 100, -1));

        txtCodigo.setEditable(false);
        txtCodigo.setBackground(new java.awt.Color(84, 84, 84));
        txtCodigo.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        txtCodigo.setForeground(new java.awt.Color(153, 153, 153));
        txtCodigo.setBorder(null);
        jPanel2.add(txtCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 90, 30));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 220, 10));

        txtIdCliente.setEditable(false);
        txtIdCliente.setBackground(new java.awt.Color(84, 84, 84));
        txtIdCliente.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        txtIdCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtIdCliente.setBorder(null);
        jPanel2.add(txtIdCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 60, 30));

        jLabel5.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Descripcion");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 90, -1));

        jLabel7.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("ID");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 40, -1));

        txtNombreCliente.setEditable(false);
        txtNombreCliente.setBackground(new java.awt.Color(84, 84, 84));
        txtNombreCliente.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        txtNombreCliente.setForeground(new java.awt.Color(153, 153, 153));
        txtNombreCliente.setBorder(null);
        jPanel2.add(txtNombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, 160, 30));

        txtPreciou.setEditable(false);
        txtPreciou.setBackground(new java.awt.Color(84, 84, 84));
        txtPreciou.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        txtPreciou.setForeground(new java.awt.Color(153, 153, 153));
        txtPreciou.setBorder(null);
        jPanel2.add(txtPreciou, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, 100, 30));

        tablaDetalles.setFont(new java.awt.Font("Source Serif Pro", 0, 12)); // NOI18N
        tablaDetalles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio unit", "Precio total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaDetalles.setRowHeight(25);
        tablaDetalles.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaDetalles.setShowVerticalLines(false);
        tablaDetalles.getTableHeader().setReorderingAllowed(false);
        tablaDetalles.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaDetallesMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(tablaDetalles);

        tablaProductos.setFont(new java.awt.Font("Source Serif Pro", 0, 12)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Stock", "Precio unit"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaProductos.setRowHeight(25);
        tablaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaProductos.setShowVerticalLines(false);
        tablaProductos.getTableHeader().setReorderingAllowed(false);
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaProductosMousePressed(evt);
            }
        });
        jScrollPane3.setViewportView(tablaProductos);

        jPanel8.setBackground(new java.awt.Color(51, 153, 255));

        lblTotalAPagar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalAPagar.setText("0");

        jLabel10.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel10.setText("Total a pagar:");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(lblTotalAPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        tablaClientes.setFont(new java.awt.Font("Source Serif Pro", 0, 12)); // NOI18N
        tablaClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Cuil"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClientes.setRowHeight(25);
        tablaClientes.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaClientes.setShowVerticalLines(false);
        tablaClientes.getTableHeader().setReorderingAllowed(false);
        tablaClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaClientesMousePressed(evt);
            }
        });
        jScrollPane4.setViewportView(tablaClientes);

        txtBuscarProducto.setMaximumSize(new java.awt.Dimension(7, 20));
        txtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Buscar producto");

        lblLimpiarBusquedaProducto.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 18)); // NOI18N
        lblLimpiarBusquedaProducto.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpiarBusquedaProducto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpiarBusquedaProducto.setText("X");
        lblLimpiarBusquedaProducto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        lblLimpiarBusquedaProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiarBusquedaProductoMouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Buscar cliente");

        txtBuscarCliente.setMaximumSize(new java.awt.Dimension(7, 20));
        txtBuscarCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarClienteKeyReleased(evt);
            }
        });

        lblLimpiarBusquedaCliente.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 18)); // NOI18N
        lblLimpiarBusquedaCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpiarBusquedaCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpiarBusquedaCliente.setText("X");
        lblLimpiarBusquedaCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        lblLimpiarBusquedaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiarBusquedaClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtBuscarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLimpiarBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(19, 19, 19)
                        .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLimpiarBusquedaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(lblLimpiarBusquedaCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)
                            .addComponent(lblLimpiarBusquedaProducto))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu1.setText("Menu");

        menuProductos.setText("Productos");
        menuProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosActionPerformed(evt);
            }
        });
        jMenu1.add(menuProductos);

        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        jMenu1.add(menuClientes);

        menuMaestroDetalle.setText("MaestroDetalle");
        menuMaestroDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaestroDetalleActionPerformed(evt);
            }
        });
        jMenu1.add(menuMaestroDetalle);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosActionPerformed
        ControladorNuevoDetalle.NuevaVistaProducto();
        ControladorNuevoDetalle.CerrarVista(this);
    }//GEN-LAST:event_menuProductosActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        ControladorNuevoDetalle.NuevaVistaCliente();
        ControladorNuevoDetalle.CerrarVista(this);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuMaestroDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaestroDetalleActionPerformed
        ControladorNuevoDetalle.NuevaVistaMaestroDetalle();
        ControladorNuevoDetalle.CerrarVista(this);
    }//GEN-LAST:event_menuMaestroDetalleActionPerformed

    private void tablaClientesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClientesMousePressed
        ControladorNuevoDetalle.LlenarCamposCliente(tablaClientes, txtIdCliente, txtNombreCliente);
        ControladorNuevoDetalle.DesactivarTabla(tablaClientes);
        ControladorNuevoDetalle.ActivarDesactivarBotonFacturar(btnFacturar, txtIdCliente, tablaDetalles);
    }//GEN-LAST:event_tablaClientesMousePressed

    private void tablaProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMousePressed
        ControladorNuevoDetalle.LimpiarCampos(txtCodigo, txtDescripcion, txtCantidad, txtPreciou);
        ControladorNuevoDetalle.LlenarCamposProducto(tablaProductos, txtCodigo, txtDescripcion, txtCantidad, txtPreciou);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnAñadir, tablaProductos);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnCancelar, tablaProductos);
    }//GEN-LAST:event_tablaProductosMousePressed

    private void tablaDetallesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaDetallesMousePressed
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnQuitar, tablaDetalles);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnCancelar, tablaDetalles);
    }//GEN-LAST:event_tablaDetallesMousePressed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        ControladorNuevoDetalle.LimpiarCampos(txtCodigo, txtDescripcion, txtCantidad, txtPreciou);
        ControladorNuevoDetalle.DesseleccionarFila(tablaProductos);
        ControladorNuevoDetalle.DesseleccionarFila(tablaDetalles);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnCancelar, tablaProductos);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnAñadir, tablaProductos);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnQuitar, tablaDetalles);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnFacturarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturarActionPerformed
        ControladorNuevoDetalle.facturar(tablaDetalles, Integer.parseInt(txtIdCliente.getText()));
        ControladorNuevoDetalle.IniciarTablaDetalles(tablaDetalles);
        ControladorNuevoDetalle.LimpiarCampos(txtCodigo, txtDescripcion, txtCantidad, txtPreciou);
        ControladorNuevoDetalle.LimpiarCamposCliente(txtIdCliente, txtNombreCliente);
        ControladorNuevoDetalle.GetTotalAPagar(tablaDetalles, lblTotalAPagar);
        ControladorNuevoDetalle.ActivarTabla(tablaClientes);
        ControladorNuevoDetalle.DesseleccionarFila(tablaClientes);
        ControladorNuevoDetalle.DesseleccionarFila(tablaProductos);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnAñadir, tablaProductos);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnQuitar, tablaDetalles);
        ControladorNuevoDetalle.ActivarDesactivarBotonFacturar(btnFacturar, txtIdCliente, tablaClientes);
        ControladorNuevoDetalle.ActualizarTablaProductos(tablaProductos);
        ControladorNuevoDetalle.VaciarBusqueda(txtBuscarCliente);
        ControladorNuevoDetalle.BuscarCliente(tablaClientes, txtBuscarCliente);
        ControladorNuevoDetalle.AjustarTabla(tablaProductos);
        ControladorNuevoDetalle.AjustarTabla(tablaDetalles);
        ControladorNuevoDetalle.AjustarTabla(tablaClientes);
    }//GEN-LAST:event_btnFacturarActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitarActionPerformed
        ControladorNuevoDetalle.EliminarDeTabla(tablaDetalles);
        ControladorNuevoDetalle.GetTotalAPagar(tablaDetalles, lblTotalAPagar);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnQuitar, tablaDetalles);
        ControladorNuevoDetalle.ActivarDesactivarBotonFacturar(btnFacturar, txtIdCliente, tablaDetalles);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnCancelar, tablaProductos);
        ControladorNuevoDetalle.AjustarTabla(tablaDetalles);
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnAñadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAñadirActionPerformed
        ControladorNuevoDetalle.AgregarEnTabla((DefaultTableModel) tablaDetalles.getModel(), Integer.parseInt(txtCodigo.getText()), txtDescripcion.getText(), Integer.parseInt(txtCantidad.getText()), Integer.parseInt(txtPreciou.getText()), tablaProductos);
        ControladorNuevoDetalle.LimpiarCampos(txtCodigo, txtDescripcion, txtCantidad, txtPreciou);
        ControladorNuevoDetalle.GetTotalAPagar(tablaDetalles, lblTotalAPagar);
        ControladorNuevoDetalle.DesseleccionarFila(tablaProductos);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnAñadir, tablaProductos);
        ControladorNuevoDetalle.ActivarDesactivarBotonFacturar(btnFacturar, txtIdCliente, tablaDetalles);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnCancelar, tablaProductos);
        ControladorNuevoDetalle.AjustarTabla(tablaDetalles);
    }//GEN-LAST:event_btnAñadirActionPerformed

    private void btnCancelarCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCompraActionPerformed
        ControladorNuevoDetalle.LimpiarCampos(txtCodigo, txtDescripcion, txtCantidad, txtPreciou);
        ControladorNuevoDetalle.LimpiarCamposCliente(txtIdCliente, txtNombreCliente);
        ControladorNuevoDetalle.IniciarTablaDetalles(tablaDetalles);
        ControladorNuevoDetalle.GetTotalAPagar(tablaDetalles, lblTotalAPagar);
        ControladorNuevoDetalle.ActivarTabla(tablaClientes);
        ControladorNuevoDetalle.DesseleccionarFila(tablaClientes);
        ControladorNuevoDetalle.DesseleccionarFila(tablaProductos);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnAñadir, tablaProductos);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnQuitar, tablaDetalles);
        ControladorNuevoDetalle.ActivarDesactivarBoton(btnCancelar, tablaProductos);
        ControladorNuevoDetalle.ActivarDesactivarBotonFacturar(btnFacturar, txtIdCliente, tablaDetalles);
        ControladorNuevoDetalle.VaciarBusqueda(txtBuscarCliente);
        ControladorNuevoDetalle.VaciarBusqueda(txtBuscarProducto);
        ControladorNuevoDetalle.BuscarCliente(tablaClientes, txtBuscarCliente);
        ControladorNuevoDetalle.BuscarProducto(tablaProductos, txtBuscarProducto);
        ControladorNuevoDetalle.AjustarTabla(tablaDetalles);
        ControladorNuevoDetalle.AjustarTabla(tablaClientes);
    }//GEN-LAST:event_btnCancelarCompraActionPerformed

    private void lblLimpiarBusquedaProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarBusquedaProductoMouseClicked
        ControladorNuevoDetalle.VaciarBusqueda(txtBuscarProducto);
        ControladorNuevoDetalle.BuscarProducto(tablaProductos, txtBuscarProducto);
    }//GEN-LAST:event_lblLimpiarBusquedaProductoMouseClicked

    private void txtBuscarProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyReleased
        ControladorNuevoDetalle.BuscarProducto(tablaProductos, txtBuscarProducto);
        //ControladorNuevoDetalle.AjustarTabla(tablaProductos);
    }//GEN-LAST:event_txtBuscarProductoKeyReleased

    private void txtBuscarClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarClienteKeyReleased
        ControladorNuevoDetalle.BuscarCliente(tablaClientes, txtBuscarCliente);
        //ControladorNuevoDetalle.AjustarTabla(tablaClientes);
    }//GEN-LAST:event_txtBuscarClienteKeyReleased

    private void lblLimpiarBusquedaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarBusquedaClienteMouseClicked
        ControladorNuevoDetalle.VaciarBusqueda(txtBuscarCliente);
        ControladorNuevoDetalle.BuscarCliente(tablaClientes, txtBuscarCliente);
    }//GEN-LAST:event_lblLimpiarBusquedaClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaNuevoDetalle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaNuevoDetalle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAñadir;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCancelarCompra;
    private javax.swing.JButton btnFacturar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lblLimpiarBusquedaCliente;
    private javax.swing.JLabel lblLimpiarBusquedaProducto;
    private javax.swing.JLabel lblTotalAPagar;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuMaestroDetalle;
    private javax.swing.JMenuItem menuProductos;
    private javax.swing.JTable tablaClientes;
    private javax.swing.JTable tablaDetalles;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtBuscarCliente;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtCodigo;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtIdCliente;
    private javax.swing.JTextField txtNombreCliente;
    private javax.swing.JTextField txtPreciou;
    // End of variables declaration//GEN-END:variables
}
