package vista;

import controlador.ControladorProducto;

public class VistaProducto extends javax.swing.JFrame {

    /**
     * Creates new form VistaProducto
     */
    public VistaProducto() {
        initComponents();
        ControladorProducto.ActualizarGrilla(tablaProductos, btnVerOcultarTodos);
        ControladorProducto.AjustarTabla(tablaProductos);
        ControladorProducto.ValidarDescripcion(txtDescripcion);
        ControladorProducto.ValidarEntero(txtCantidad);
        ControladorProducto.ValidarEntero(txtPrecio);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        txtCantidad = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnEliminar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnActivarDesactivar = new javax.swing.JButton();
        btnVerOcultarTodos = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaProductos = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        txtBuscarProducto = new javax.swing.JTextField();
        lblLimpiarBusquedaCliente = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        menuClientes = new javax.swing.JMenuItem();
        menuNuevoDetalle = new javax.swing.JMenuItem();
        menuMaestroDetalle = new javax.swing.JMenuItem();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(41, 41, 41));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Productos", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 36), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));

        jPanel2.setBackground(new java.awt.Color(84, 84, 84));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nuevo Producto");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 258, -1));

        jLabel3.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Descripcion");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, -1));

        txtDescripcion.setBackground(new java.awt.Color(84, 84, 84));
        txtDescripcion.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        txtDescripcion.setForeground(new java.awt.Color(153, 153, 153));
        txtDescripcion.setBorder(null);
        txtDescripcion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDescripcionKeyReleased(evt);
            }
        });
        jPanel2.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 220, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 220, 10));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 220, 10));

        txtCantidad.setBackground(new java.awt.Color(84, 84, 84));
        txtCantidad.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        txtCantidad.setForeground(new java.awt.Color(153, 153, 153));
        txtCantidad.setBorder(null);
        txtCantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCantidadKeyReleased(evt);
            }
        });
        jPanel2.add(txtCantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 220, 30));

        jLabel4.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cantidad");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 70, -1));

        jLabel6.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 55, -1));

        txtPrecio.setBackground(new java.awt.Color(84, 84, 84));
        txtPrecio.setFont(new java.awt.Font("Source Sans Pro Semibold", 0, 14)); // NOI18N
        txtPrecio.setForeground(new java.awt.Color(153, 153, 153));
        txtPrecio.setBorder(null);
        txtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPrecioKeyReleased(evt);
            }
        });
        jPanel2.add(txtPrecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 220, 30));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 220, 10));

        btnEliminar.setText("Eliminar");
        btnEliminar.setEnabled(false);
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 310, 130, -1));

        btnGuardar.setText("Guardar");
        btnGuardar.setEnabled(false);
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(btnGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 130, -1));

        btnCancelar.setText("Cancelar");
        btnCancelar.setEnabled(false);
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 130, -1));

        btnActivarDesactivar.setText("Activar/Desactivar");
        btnActivarDesactivar.setEnabled(false);
        btnActivarDesactivar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActivarDesactivarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActivarDesactivar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, 130, -1));

        btnVerOcultarTodos.setText("Mostrar Inactivos");
        btnVerOcultarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerOcultarTodosActionPerformed(evt);
            }
        });
        jPanel2.add(btnVerOcultarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 430, 130, -1));

        tablaProductos.setFont(new java.awt.Font("Source Serif Pro", 0, 12)); // NOI18N
        tablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Descripcion", "Cantidad", "Precio", "Activo"
            }
        ));
        tablaProductos.setRowHeight(25);
        tablaProductos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tablaProductos.setShowVerticalLines(false);
        tablaProductos.getTableHeader().setReorderingAllowed(false);
        tablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaProductosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tablaProductos);

        jLabel9.setFont(new java.awt.Font("Source Serif Pro Semibold", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Buscar producto");

        txtBuscarProducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtBuscarProductoKeyReleased(evt);
            }
        });

        lblLimpiarBusquedaCliente.setFont(new java.awt.Font("Source Code Pro Semibold", 1, 18)); // NOI18N
        lblLimpiarBusquedaCliente.setForeground(new java.awt.Color(255, 255, 255));
        lblLimpiarBusquedaCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLimpiarBusquedaCliente.setText("X");
        lblLimpiarBusquedaCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        lblLimpiarBusquedaCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblLimpiarBusquedaClienteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 345, Short.MAX_VALUE)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblLimpiarBusquedaCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(lblLimpiarBusquedaCliente))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
                .addContainerGap())
        );

        jMenu3.setText("Menu");

        menuClientes.setText("Clientes");
        menuClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuClientesActionPerformed(evt);
            }
        });
        jMenu3.add(menuClientes);

        menuNuevoDetalle.setText("NuevoDetalle");
        menuNuevoDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuNuevoDetalleActionPerformed(evt);
            }
        });
        jMenu3.add(menuNuevoDetalle);

        menuMaestroDetalle.setText("MaestroDetalle");
        menuMaestroDetalle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuMaestroDetalleActionPerformed(evt);
            }
        });
        jMenu3.add(menuMaestroDetalle);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        ControladorProducto.AgregarModificar(tablaProductos, txtDescripcion.getText(), Integer.parseInt(txtCantidad.getText()), Integer.parseInt(txtPrecio.getText()));
        ControladorProducto.ActualizarGrilla(tablaProductos, btnVerOcultarTodos);
        ControladorProducto.AjustarTabla(tablaProductos);
        ControladorProducto.LimpiarCampos(txtDescripcion, txtCantidad, txtPrecio);
        ControladorProducto.DesactivarBoton(btnGuardar);
        ControladorProducto.DesactivarBoton(btnEliminar);
        ControladorProducto.DesactivarBoton(btnCancelar);
        ControladorProducto.ActivarDesactivarTxtDescripcion(txtDescripcion, tablaProductos);
        ControladorProducto.ActivarTabla(tablaProductos);
        ControladorProducto.VaciarBusqueda(txtBuscarProducto);
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        ControladorProducto.Eliminar(tablaProductos);
        ControladorProducto.ActualizarGrilla(tablaProductos, btnVerOcultarTodos);
        ControladorProducto.AjustarTabla(tablaProductos);
        ControladorProducto.LimpiarCampos(txtDescripcion, txtCantidad, txtPrecio);
        ControladorProducto.DesactivarBoton(btnGuardar);
        ControladorProducto.DesactivarBoton(btnEliminar);
        ControladorProducto.DesactivarBoton(btnCancelar);
        ControladorProducto.ActivarDesactivarTxtDescripcion(txtDescripcion, tablaProductos);
        ControladorProducto.ActivarDesactivarBotonActivarDesactivar(tablaProductos, btnActivarDesactivar);
        ControladorProducto.ActivarTabla(tablaProductos);
        ControladorProducto.VaciarBusqueda(txtBuscarProducto);
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        ControladorProducto.DesseleccionarFila(tablaProductos);
        ControladorProducto.LimpiarCampos(txtDescripcion, txtCantidad, txtPrecio);
        ControladorProducto.DesactivarBoton(btnGuardar);
        ControladorProducto.DesactivarBoton(btnEliminar);
        ControladorProducto.DesactivarBoton(btnCancelar);
        ControladorProducto.ActivarDesactivarTxtDescripcion(txtDescripcion, tablaProductos);
        ControladorProducto.ActivarDesactivarBotonActivarDesactivar(tablaProductos, btnActivarDesactivar);
        ControladorProducto.ActivarTabla(tablaProductos);
        ControladorProducto.VaciarBusqueda(txtBuscarProducto);
        ControladorProducto.BuscarProducto(tablaProductos, txtBuscarProducto);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDescripcionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDescripcionKeyReleased
        ControladorProducto.ActivarDesactivarBotonGuardar(btnGuardar, txtDescripcion, txtCantidad, txtPrecio);
        ControladorProducto.ActivarDesactivarBotonCancelar(btnCancelar, txtDescripcion, txtCantidad, txtPrecio, tablaProductos, txtBuscarProducto);
    }//GEN-LAST:event_txtDescripcionKeyReleased

    private void txtCantidadKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCantidadKeyReleased
        ControladorProducto.ActivarDesactivarBotonGuardar(btnGuardar, txtDescripcion, txtCantidad, txtPrecio);
        ControladorProducto.ActivarDesactivarBotonCancelar(btnCancelar, txtDescripcion, txtCantidad, txtPrecio, tablaProductos, txtBuscarProducto);
    }//GEN-LAST:event_txtCantidadKeyReleased

    private void txtPrecioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPrecioKeyReleased
        ControladorProducto.ActivarDesactivarBotonGuardar(btnGuardar, txtDescripcion, txtCantidad, txtPrecio);
        ControladorProducto.ActivarDesactivarBotonCancelar(btnCancelar, txtDescripcion, txtCantidad, txtPrecio, tablaProductos, txtBuscarProducto);
    }//GEN-LAST:event_txtPrecioKeyReleased

    private void tablaProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaProductosMousePressed
        ControladorProducto.LimpiarCampos(txtDescripcion, txtCantidad, txtPrecio);
        ControladorProducto.LlenarCampos(tablaProductos, txtDescripcion, txtCantidad, txtPrecio);
        ControladorProducto.ActivarBoton(btnEliminar);
        ControladorProducto.ActivarBoton(btnCancelar);
        ControladorProducto.ActivarDesactivarTxtDescripcion(txtDescripcion, tablaProductos);
        ControladorProducto.ActivarDesactivarBotonActivarDesactivar(tablaProductos, btnActivarDesactivar);
        ControladorProducto.DesactivarTabla(tablaProductos);
    }//GEN-LAST:event_tablaProductosMousePressed

    private void menuNuevoDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoDetalleActionPerformed
        ControladorProducto.NuevaVistaNuevoDetalle();
        ControladorProducto.CerrarVista(this);
    }//GEN-LAST:event_menuNuevoDetalleActionPerformed

    private void menuClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuClientesActionPerformed
        ControladorProducto.NuevaVistaCliente();
        ControladorProducto.CerrarVista(this);
    }//GEN-LAST:event_menuClientesActionPerformed

    private void menuMaestroDetalleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuMaestroDetalleActionPerformed
        ControladorProducto.NuevaVistaMaestroDetalle();
        ControladorProducto.CerrarVista(this);
    }//GEN-LAST:event_menuMaestroDetalleActionPerformed

    private void btnActivarDesactivarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActivarDesactivarActionPerformed
        ControladorProducto.ActivarDesactivarProducto(tablaProductos);
        ControladorProducto.ActualizarGrilla(tablaProductos, btnVerOcultarTodos);
        ControladorProducto.AjustarTabla(tablaProductos);
        ControladorProducto.ActivarDesactivarBotonActivarDesactivar(tablaProductos, btnActivarDesactivar);       
        //todo lo que esta en el boton cancelar
        ControladorProducto.DesseleccionarFila(tablaProductos);
        ControladorProducto.LimpiarCampos(txtDescripcion, txtCantidad, txtPrecio);
        ControladorProducto.DesactivarBoton(btnGuardar);
        ControladorProducto.DesactivarBoton(btnEliminar);
        ControladorProducto.DesactivarBoton(btnCancelar);
        ControladorProducto.ActivarDesactivarTxtDescripcion(txtDescripcion, tablaProductos);
    }//GEN-LAST:event_btnActivarDesactivarActionPerformed

    private void btnVerOcultarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerOcultarTodosActionPerformed
        ControladorProducto.VerOcultarTodos(tablaProductos, btnVerOcultarTodos);
        ControladorProducto.AjustarTabla(tablaProductos);
        ControladorProducto.LimpiarCampos(txtDescripcion, txtCantidad, txtPrecio);
        ControladorProducto.DesactivarBoton(btnGuardar);
        ControladorProducto.DesactivarBoton(btnEliminar);
        ControladorProducto.DesactivarBoton(btnCancelar);
        ControladorProducto.ActivarDesactivarTxtDescripcion(txtDescripcion, tablaProductos);
        ControladorProducto.ActivarDesactivarBotonActivarDesactivar(tablaProductos, btnActivarDesactivar);
    }//GEN-LAST:event_btnVerOcultarTodosActionPerformed

    private void txtBuscarProductoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtBuscarProductoKeyReleased
        ControladorProducto.BuscarProducto(tablaProductos, txtBuscarProducto);
        ControladorProducto.ActivarDesactivarBotonCancelar(btnCancelar, txtDescripcion, txtCantidad, txtPrecio, tablaProductos, txtBuscarProducto);

    }//GEN-LAST:event_txtBuscarProductoKeyReleased

    private void lblLimpiarBusquedaClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLimpiarBusquedaClienteMouseClicked
        ControladorProducto.VaciarBusqueda(txtBuscarProducto);
        ControladorProducto.BuscarProducto(tablaProductos, txtBuscarProducto);
        ControladorProducto.ActivarDesactivarBotonCancelar(btnCancelar, txtDescripcion, txtCantidad, txtPrecio, tablaProductos, txtBuscarProducto);

    }//GEN-LAST:event_lblLimpiarBusquedaClienteMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActivarDesactivar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnVerOcultarTodos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblLimpiarBusquedaCliente;
    private javax.swing.JMenuItem menuClientes;
    private javax.swing.JMenuItem menuMaestroDetalle;
    private javax.swing.JMenuItem menuNuevoDetalle;
    private javax.swing.JTable tablaProductos;
    private javax.swing.JTextField txtBuscarProducto;
    private javax.swing.JTextField txtCantidad;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtPrecio;
    // End of variables declaration//GEN-END:variables
}
